### ISSUE TITLE
Ray/Shapecast a single shape by ID

### ISSUE THREAD

**Issue by ShockSlayer** [erincatto/box2c#100]
In v2.4 I was able to collect a list of fixtures, and then raycast their shapes directly, without needing to know the shape type. It looks like there isn't a way to do this currently.

My use case was some basic line of sight checking for targeting. I would use QueryAABB to get everything in range of an object, filtering everything into two lists: fixtures marked as "hurtboxes," and fixtures marked as capable of blocking line of sight. Then to find the closest valid target, I would use body positions to determine a ray, and cast against anything in the "block line of sight" list; continually adjusting the maxFraction from any hits, before finally using that possibly-shorter ray to cast against the "hurtbox" fixtures to see if they still hit.

Probably not the most accurate approach, but it worked well enough for my use. With v3 adding b2World_OverlapPolygon, I am wondering if a visibility polygon approach might be more accurate and efficient. But I still think it would be beneficial to have something like a b2Shape_RayCast function. This could possibly also apply to shapecasting.

**Comment by erincatto** [comment]
#119
