### ISSUE TITLE
Joint parameter getters and setters

### ISSUE THREAD

**Issue by ShockSlayer** [erincatto/box2c#101]
I'd like to recover as many of these as reasonably possible. In my engine, I've specifically wrapped all joint getters and setters from v2.4 in the scripting engine, in order to easily monitor and variably configure joints, based on a variety of different gameplay conditions. Additionally, I have some joint configurations that are designated as renderable in relation to their connected bodies; in these cases I recover even the generic joint data like the local anchor points and transform them using an array of body transforms, which are adjusted for visual interpolation.

I probably can't make a proper use case for getting and setting every single joint parameter at this time, since I've focused more on engine development than the creative process, however I think joints are where Box2D really shines and I wanted to express a desire to see that level of control make its way back. I figured it would also be easier to ask for another pass and then fill in any remaining blanks from there, if that makes sense.

A few examples that have popped up thusfar would be like b2DistanceJoint_SetLength, which takes all 3 length parameters, but if say only minLength needs to be changed, there is no way to recover what the other two were. b2DistanceJoint_SetTuning is in the same boat. There are also no functions to check or adjust a weld joint after creation.

EDIT: I'd also like for joint user data to return if that's reasonable to do.

**Comment by erincatto** [comment]
#119
