### ISSUE TITLE
Expose b2MakeShapeDistanceProxy for ease of use with b2TimeOfImpact

### ISSUE THREAD

**Issue by Ughuuu** [erincatto/box2c#121]
I am trying to get a time of impact by calling, `b2TimeOfImpact`. I need for this a `b2DistanceProxy`. I would very much prefer to reuse the function: `b2MakeShapeDistanceProxy`.

However this is in the src. What it does is not complicated, however I see it's using the `b2Shape*` directly. For this I need yet more stuff from internal API(eg. get a shape and a world).

So I either use the internal API, or I store the same data myself(About the shape) or I just query for them using box2d API(eg. getShapeType, etc).

**Comment by erincatto** [comment]
Have you considered using functions like `b2World_CapsuleCast`? What is your use case?

I'm not opposed to adding something like `b2Shape_MakeDistanceProxy`.

**Comment by Ughuuu** [comment]
Havent checked that. I need to do shape cast with all shapes pretty much(polygon, circle, capsule, etc). Does it work with all shape types?

**Comment by erincatto** [comment]
Yes, you implement this callback and it receives the fraction along the cast where the hit occurs:
```c
b2CastResultFcn(b2ShapeId shapeId, b2Vec2 point, b2Vec2 normal, float fraction, void* context);
```
This sample shows all the details:
https://github.com/erincatto/box2c/blob/412d501a8855a75ec2edddad8d08f684d75e83c6/samples/sample_collision.cpp#L1384

**Comment by erincatto** [comment]
I'm going to close this for now. Feel free to re-open if those world cast functions don't meet your needs.
