### ISSUE TITLE
Expose more functions at API for bodies

### ISSUE THREAD

**Issue by Ughuuu** [erincatto/box2c#122]
The following functions aren't exposed and the body can't change these unless destroyed and recreated.

void b2Body::SetBullet(bool flag);
bool b2Body::IsBullet() const;

void b2Body::SetAwake(bool flag);

void b2Body::SetFixedRotation(bool flag);
bool b2Body::IsFixedRotation() const;

**Comment by erincatto** [comment]
Duplicate of #111
