### ISSUE TITLE
Invisible kinematic bodies in b2DebugDraw

### ISSUE THREAD

**Issue by MetGang** [erincatto/box2c#136]
While creating wrapper around b2DebugDraw I noticed that kinematic bodies are invisible if don't alter their alpha value while rendering them. Turns out kinematic bodies are the only ones where color is created from literal instead of with `b2MakeColor` resulting alpha value to be unspecified (mostly 0).

Here's offending line, looks like simple oversight.
https://github.com/erincatto/box2c/blob/main/src/world.c#L726

**Comment by erincatto** [comment]
It looks like this is already fixed. Thanks for the report!
