### ISSUE TITLE
Allow minimal builds without FetchContent

### ISSUE THREAD

**Issue by HolyBlackCat** [erincatto/box2c#144]
Hello! Currently it's not possible to build box2d without internet connection, unless you've downloaded all dependencies in advance. 

1. Even when both tests and samples are disabled, it still tries to pull enkiTS, though it shouldn't be needed for anything.
2. If you're building the static library, there's no way to disable tests and remove dependency on enkiTS.

So I suggest adding a CMake flag to disable tests, and not pulling enkiTS if it's not needed. I can make a PR if you're ok with this.

**Comment by erincatto** [comment]
This shouldn't happen with this check:
https://github.com/erincatto/box2c/blob/1fb2988f102d88430fea60447475b276b73578cc/CMakeLists.txt#L44C1-L44C56

**Comment by HolyBlackCat** [comment]
@erincatto It works only if box2d is used from another CMake project. But doesn't work when building box2d directly (to use with other build systems).

**Comment by erincatto** [comment]
Fair enough. I can change this so building unit tests is an option.

**Comment by erincatto** [comment]
Fixed in #149
