### ISSUE TITLE
Question about assert in solver_set.c

### ISSUE THREAD

**Issue by nagolove** [erincatto/box2c#162]
Hello Erin! I have some problems in my project which use box2c. I get this [assert](https://github.com/erincatto/box2c/blob/dd6097fc9f707e30b2045c39427d15dd93b7c8b1/src/solver_set.c#L300) in my scene after some time. Could your explain by simple words meaning of this condition? It would be great to put description to the code if someone has some problem.

**Comment by erincatto** [comment]
Hi, this is an internal bug and not something for you to fix on your end. Please try running with `B2_VALIDATE == 1` (CMake option BOX2D_VALIDATE) and see if you catch the bug earlier.

**Comment by erincatto** [comment]
Hmm, I wonder if this is due to a sensor falling asleep.

**Comment by erincatto** [comment]
Yup, it was a sensor bug. Fixing this here: #165
