### ISSUE TITLE
Minor Documentation Issues

### ISSUE THREAD

**Issue by garethyr** [erincatto/box2c#167]
The new documentation is great! It's got a few minor issues though:

1. I found a few tiny typos that I figured I should mention.
![image](https://github.com/erincatto/box2c/assets/7739094/5d61b071-73a2-4fb1-bd71-a152557909bc)
![image](https://github.com/erincatto/box2c/assets/7739094/c8033a86-9b95-431c-89f6-592f31227ef2)
![image](https://github.com/erincatto/box2c/assets/7739094/2aa6ded3-d1a5-4a7e-a363-2bac3fbafa14)
2. I didn't see any mention of Explosions in the docs. I guess the large world testbed uses them, but it might be nice to have them mentioned somewhere.
3. There's no mention of the new springs on revolute or prismatic joints.

**Comment by erincatto** [comment]
Thanks. Fixed in #174.

The written portion of the manual is for new users and not meant to be exhaustive. I try to demonstrate and test every feature in the samples and add doxygen comments.

The explosion feature is a bit crude now and I will likely enhance it in the future.
