### ISSUE TITLE
Dynamic Poly Shape Tunneling Through Chain Shapes

### ISSUE THREAD

**Issue by StefDevs** [erincatto/box2c#172]
As discussed on discord, when using a poly shape for my player character there is a relatively common occurrence of situations where it will pass straight through certain spots on chain shapes.

![b2d_chain_tunneling](https://github.com/user-attachments/assets/e44fa0b2-76c2-45d8-9978-426b8e13d110)

![b2d_chain_tunneling_detailed](https://github.com/user-attachments/assets/e4129d3f-f5ea-4f03-bd09-994f90fe0e27)

The collision works consistently on different spots of the same chain segment with the same dynamic body - it's just certain specific locations where the issue occurs. It's pretty easy to come across one of these spots, and they are consistently repeatable once found. That said, I haven't been able to identify any pattern of where these spots occur.

![b2d_chain_tunneling_variance](https://github.com/user-attachments/assets/820c86c1-1063-4ca8-878f-d99bdc0017fc)

b2Body_SetAngularVelocity, b2Body_SetTransform, and b2Body_SetLinearVelocity are being called every frame albeit with very small or zero deltas. Testing with these calls eliminated indicates that they are likely unrelated. Also note that removing the angular velocity has no effect on the problem.

The sim is running at 125hz with  substeps set to 1.

Testing shows that the problem may not be present when using a circle instead of a polygon, though this testing has not yet been super thorough.

The exact geometry of the player polygon in this example:
```
-0.328125 ,  0.179688
-0.203125 ,  0.304688
 0.171875 ,  0.304688
 0.359375 ,  0.117188
 0.359375 , -0.195313
 0.234375 , -0.320313
-0.265625 , -0.257813
-0.328125 , -0.132813
```

As for the chain geometry, the problem is reproduceable with the vertical edge of a simple square-shaped closed chain. I have tested primarily on a vertical edge like this, but the bug is not limited to this and does occur on all sorts of other edges as well.

Another potentially notable fact is that the player body is initially created with a simple circle shape which is then replaced by the polygon later in the simulation via b2Shape_SetPolygon. However, the collider shape in this example is not being updated while the player is airborne, so not within 100 frames of when the collision should occur. When the circle shape is used, b2Shape_SetPolygon is never called, so this could be an important difference. I may test this further.

Here is the b2Polygon supplied to b2Shape_SetPolygon:
```
    vertices = [(same as listed above)];
    normals = [{0.707107, -0.707107}, {0, -1}, {-0.707107, -0.707107}, {-1, -0}, {-0.707107, 0.707107}, {0.124035, 0.992278}, {0.894427, 0.447214}, {1, -0}];
    centroid = {0.013825, -0.00225};
    radius = 0;
    count = 8;
```

And here is the body and shape definitions the body is created with initially (along with b2CreateCircleShape with simple circle inputs):
```
bodyDef  = {
    type = dynamicBody;
    position = {0, 0};
    angle = 0;
    linearVelocity = {0, 0};
    angularVelocity = 0;
    linearDamping = 0;
    angularDamping = 0;
    gravityScale = 1;
    sleepThreshold = 0.05;
    userData = 5_0000_0000_0001;
    enableSleep = false;
    isAwake = true;
    fixedRotation = true;
    isBullet = false;
    isEnabled = true;
    automaticMass = true;
    internalValue = 1152023;
}
shapeDef = {
    userData = 5_0000_0000_0001;
    friction = 0.5;
    restitution = 0.35;
    density = 1;
    filter = {
        categoryBits = 2;
        maskBits = 4294967295;
        groupIndex = 0;
    };
    isSensor = false;
    enableSensorEvents = true;
    enableContactEvents = true;
    enableHitEvents = false;
    enablePreSolveEvents = false;
    forceContactCreation = false;
    internalValue = 1152023;
}
```

Let me know if there is anything else I can do to help reproduce this case.

**Comment by StefDevs** [comment]
Update: I noticed that the polygon's normals are inverted. Reversing them directly had no effect, but correcting the hull which is passed to b2MakePolygon to be in CCW order does _appear_ to solve the issue. 

I thought my hulls were CCW, but they we being y-flipped, making them CW.

I'm not sure I remember seeing it stated anywhere that hulls need to be CCW, but I'm guessing this would have been caught by b2ValidateHull, which I wasn't using.

**Comment by erincatto** [comment]
Oh yeah, this is a common problem. I don't call `b2ValidateHull` when you create a polygon because it is expensive.

Did you modify the hull after calling `b2ComputeHull`? It is not supported to modify a hull after it is computed. Maybe in the future I can add some utilities to allow hulls to be inverted, transformed, etc safely.

**Comment by erincatto** [comment]
I tested your data and this doesn't assert.
```c
m_points[0] = {-0.328125, 0.179688};
m_points[1] = {-0.203125, 0.304688};
m_points[2] = {0.171875, 0.304688};
m_points[3] = {0.359375, 0.117188};
m_points[4] = {0.359375, -0.195313};
m_points[5] = {0.234375, -0.320313};
m_points[6] = {-0.265625, -0.257813};
m_points[7] = {-0.328125, -0.132813};

b2Hull hull = b2ComputeHull(m_points, 8);
assert(b2ValidateHull(&hull));
```

**Comment by StefDevs** [comment]
My apologies - I'm looking at the code _instead of relying on my memory_ and I'm not calling `b2ComputeHull` in the first place - I'm constructing the hull myself from a set of >8 points. My data listed there is already a hull (albeit a CW one), so it seems wasteful to feed it to `b2ComputeHull`.

My suggestion was actually to add optional full validation to `b2MakePolygon`. Or to catch my my specific case, CCW checking would have been sufficient and probably cheap enough to do always (you could replace the existing edge length check with corner area). Though I'm not sure just how perf-sensitive this code path is.

Just ideas, assuming my case is still within the bounds of what you call a "common issue".

**Comment by erincatto** [comment]
Your workflow is not supported.

I'm adding some warnings like this:

```c
/// Make a convex polygon from a convex hull. This will assert if the hull is not valid.
/// @warning Do not manually fill in the hull data, it must come directly from b2ComputeHull
B2_API b2Polygon b2MakePolygon(const b2Hull* hull, float radius);
```

I will add more validation to `b2MakePolygon` as well.

In version 2 the equivalent of `b2MakePolygon` computed the hull itself, but this created a situation where it needed to be very fast (and less robust). It also caused a problem where degeneracies would cause hidden failures. So I've moved to a split workflow.

**Comment by erincatto** [comment]
Added validation in #178
