### ISSUE TITLE
API Feedback

### ISSUE THREAD

**Issue by RandyGaul** [erincatto/box2c#177]
Thanks for taking the time to refactor your API with structs/handles. This has been pretty easy overall to bind to Lua and adapt. Good work on refactoring your collision routines to be public facing and making all of the useful collision functions easily accessible, including the dynamic tree.

I noticed a variety of functions are returning structs or accepting structs as parameters by value. I would recommend sticking with the by-value convention for all the functions regarding shape passing. Some of them currently accept pointers, while others are by value. It makes sense if you want to pass some by value if you've, for example, noticed a perf difference in debug mode. But for any optimized compile this isn't going to be an optimization, and at worst incur some pointer aliasing overhead. The bigger issue though was these pointers were an extra pain when binding the API to Lua. I ended up wrapping all the functions dealing with shapes by pointer with inline wrappers that deal with shapes by value. A minor thing, but still, would be a lot nicer generally if the convention was more consistent. 

This feedback also applies to b2Hull, transforms, b2RayCastInput, etc.

**Comment by RandyGaul** [comment]
Some other lingering thoughts. The _Atomic makes it a bit troublesome to compile. I noticed that pretty much all of the uses of _Atomic are on 4/8byte words and should already be atomic operations themselves, not necessitating the keyword. It would be nice if this was removed, or wrapped via overridable macros, to ease the integration into other projects. You should be able to safely remove these if you ensure byte alignment.

As far as cmake goes I had to spend extra time figuring out how to disable warnings as errors, as a number of warnings internal to Box2c were breaking the build (latest MSVC 2022).

**Comment by erincatto** [comment]
Thanks for taking time to review the API Randy!

I agree that pass by value/pointer should be consistent. Conventional wisdom seems to be that structs 16 bytes or less should be passed by value while larger structs should be passed by pointer.

I recently had another issue filed where someone wanted pass by pointer for all structs to make interfacing with Haskell easier: https://github.com/erincatto/box2c/issues/163

You need to use C17 with Box2D. On MSVC you need to enable `/experimental:c11atomics`.

I'm not supporting older MSVC compilers that don't have `/experimental:c11atomics`.

**Comment by erincatto** [comment]
I scanned the whole API again. It seems consistent according to the 16 byte rule. Did I miss something?

I'm using _return value optimization_ for larger return values. https://en.wikipedia.org/wiki/Copy_elision

But I have to admit I haven't looked at the assembly for all call sites.

**Comment by RandyGaul** [comment]
I'm not sure that conventional wisdom about byte size is very effective for a user API. Instead, from a user perspective, consistency would be strongly preferred. Either all pointers or all values. If you wanted to go the extra mile to make it easy for users to integrate, providing inline wrappers for the other option is something you might want to consider.

I know that traditional wisdom, especially in professional gamedev spheres, focuses on prioritizing optimization. However, my observation is, especially for 2D games, these kinds of hair-splitting differences aren't a priority and just add friction. From a user perspective flipping between pointers/values across a 16-byte size feels inconsistent and a little frustrating. This is pretty minor feedback overall though. I'm just offering it if you wanted to push the user experience quality bar as high as possible.

As for the license, I noticed you swapped to MIT from zlib. Is this because some other open-source libraries have used Box2D source, modified it, and licensed it without crediting you?

I want to replace some of my collision code with Box2c now that your collision APIs are easy to use without any prior object setup. So far though I've only incorporated code licensed under public domain/zlib to simplify license requirements for users (basically no consideration required from a user perspective). MIT is a little more invasive since now users would have to copy a license text file into their final product installations.

I understand if you might not want to comment about licenses. I'm just a bit new to redistributing MIT licensed code and was curious.

**Comment by RandyGaul** [comment]
Quick example of what would be really nice to see in the box2c headers:

```c
B2_API void b2Shape_SetCircle(b2ShapeId shapeId, const b2Circle* circle);
B2_API void b2Shape_SetCircle2(b2ShapeId shapeId, b2Circle circle);

B2_API void b2Shape_SetCapsule(b2ShapeId shapeId, const b2Capsule* capsule);
B2_API void b2Shape_SetCapsule2(b2ShapeId shapeId, b2Capsule capsule);

B2_API void b2Shape_SetSegment(b2ShapeId shapeId, const b2Segment* segment);
B2_API void b2Shape_SetSegment2(b2ShapeId shapeId, b2Segment segment);
```

Of course, internally in Box2c you can still abide by the 16-byte rule if you really wanted to maximize perf within Box2c's implementation.

**Comment by RandyGaul** [comment]
I noticed you remove distance cache from a few of the collision functions, like `b2CollideSegmentAndPolygon`. Is there a reason `b2CollideSmoothSegmentAndPolygon` still has this as a required parameter?

`b2DistanceJoint_IsLimitEnabled` implementation seems to be missing altogether.

**Comment by erincatto** [comment]
I don't want to add duplicate APIs to Box2D. This would cause a lot of confusion and require more testing.

There was a discussion about pass by value and people seemed to feel strongly that that API should not pass large structs by value. https://discord.com/channels/460295137705197568/1064661081903075429/1211018939132285010

I think this is one area where I cannot make everyone happy. So I will just aim for consistency.

Some collision algorithms no longer call GJK and don't benefit from a cache.

I'll implement `b2DistanceJoint_IsLimitEnabled` in the next PR.

**Comment by RandyGaul** [comment]
Thanks!
