### ISSUE TITLE
Clamping expanded radii not necessary

### ISSUE THREAD

**Issue by irlanrobson** [erincatto/box2c#49]
https://github.com/erincatto/box2c/blob/main/src/distance.c#L1045

Not sure if this is a temporary, but B2_MAX is not necessary in this line. Assuming totalRadius >= 0 then target >= b2_linearSlop always.

**Comment by erincatto** [comment]
Sorry it took me a while to look at this. In Box2D version 3 I'm supporting shapes with zero radius. In other words, the polygon skin radius from v2.4 is gone.
