### ISSUE TITLE
Feature request: One-way joints.

### ISSUE THREAD

**Issue by ShockSlayer** [erincatto/box2c#51]
As I've been developing a game around the previous version of Box2D, I've found myself wishing for "one way joints."

The best use-case I can provide is between two dynamic bodies in a platformer-type setting. You would have a primary player-controlled "body" and an auxiliary "head," connected together with two joints: distance and revolute. The revolute joint is configured to limit how much movement the head can perform, while the distance joint acts as a spring to center it.

As the player lands on a platform, the head has room to bounce down a little bit. This looks awesome. But, since it is now pulling down on the player body, if the player were to immediately jump again, the force of the joint pulling on it would reduce the next jump's height.

Since this particular set up of joints is entirely based around the effects on only one of the bodies, if it was possible to turn off the joint effects on the other, that would be excellent. I have experimented with several practical ways to try to get around this, but each seems to have its own caveats or produces a different result.

I figured I would request this early, since I would imagine that it would require adding some bools to the joint defs and that would be less API changes later.

**Comment by erincatto** [comment]
A kinematic body that follows the player using velocity targets would work, but you would need to implement that in a second Box2D world. This is necessary to keep the kinematic and the player body in sync.

**Comment by ShockSlayer** [comment]
That's a very interesting approach, and I can totally see how that would work. A second world never even occurred to me. I will have to experiment with that for sure. Hopefully there's more interest in one-way joints from other people to warrant some experimentation in the future.

**Comment by erincatto** [comment]
I'm going to close this for now. I've implemented one-way joints in the past and it was kind of a mess. If you go down this path you start needing to develop priority systems and it affects contacts as well a joints. Then you start getting strange behavior and transitive problems. For example: body A can one-way push body B which can two-way push body C which can two-way push body A

**Comment by ShockSlayer** [comment]
That makes sense, based on what I've found with my minimal experiments in v2.4. I appreciate the consideration and insights regardless!
