### ISSUE TITLE
Runtime dispatch for SSE2?

### ISSUE THREAD

**Issue by erincatto** [erincatto/box2c#60]
https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/tree/master/2020/07/16

**Comment by svercl** [comment]
I've been maintaining my own patch which uses [simde](https://github.com/simd-everywhere/simde) in place of `immintrin.h`. It only required prefixing `simde` or `SIMDE` where needed.

**Comment by erincatto** [comment]
I'll be looking at simde for Neon. I don't think it has runtime dispatch. I'll need to potentially run on PCs without AVX2 without requiring a separate build.

**Comment by erincatto** [comment]
simde implemented! Runtime dispatch may be considered later.

**Comment by erincatto** [comment]
Closing because I'm not sure how relevant runtime dispatch is.
