### ISSUE TITLE
Missing body/shape functions for dampings, gravity, filter

### ISSUE THREAD

**Issue by ShockSlayer** [erincatto/box2c#93]
Currently it looks like there's no getters or setters for existing bodies for linear damping, angular damping, or gravity scale.

EDIT: I'm also noticing that there are no functions for getting/setting the filter on existing shapes.

**Comment by ShockSlayer** [comment]
Awesome, looks like the shape filter stuff is sorted and there's now setters for the body parameters. No getters though - is this intentional?

**Comment by erincatto** [comment]
I can easily add the getters if you need them.

**Comment by ShockSlayer** [comment]
Yes please! I'm only creating issues for things I'm actively using in my engine that have gone missing between versions. I hope that's okay.

**Comment by erincatto** [comment]
Thanks for the report. See #99
