### ISSUE TITLE
Restoring/Adding helper functions for AABBs

### ISSUE THREAD

**Issue by ShockSlayer** [erincatto/box2c#94]
In v2.4 I was able to iterate over the fixtures of a body, getting AABBs from the shape, agnostic of the shape type, since ComputeAABB was part of the base class. Now it looks like the only path to replicate this behavior is to use the shapeID to get the type, then switch case that to use the shape specific compute functions in geometry.h after also getting the geometry pointers.

It looks like b2ComputeShapeAABB already exists, but isn't exposed for the user. I think it would be nice to be able to get an AABB from a shapeID and transform in a similar way.

Additionally, it would be nice to have some of the AABB helper functions back. In this same case, I would use Combine with each of these AABBs to create one large "body AABB" which I would then make sure was usable with IsValid. I'm also missing GetCenter, Contains, and b2TestOverlap.

**Comment by erincatto** [comment]
I wonder what you are using the AABBs for in your application. I might be converting these to use SIMD, so I want to hide them.

**Comment by ShockSlayer** [comment]
Current uses that are directly Box2D specific are the mouse joint query, getting world geometry around a light source for shadow casting, and finding userData around objects for various uses (like finding the closest hitbox to a target point/radius.) All of these are through QueryAABB, and as development progresses I'm certain that this list will expand as more things come up.

Most of my other uses are supplemental by comparison. The "body AABB" example from above is only used in some rendering effects. I express the game's camera as a b2AABB, and world chunks as b2AABBs, so I can use Contains and b2TestOverlap to filter out the rendering steps for any areas or objects that wouldn't be seen. I also use them to get relevant tiles around an object, and to express the range of navigational nodes so I can raycast between them to check if they should be considered connected. Also pretty much any renderable primitive rectangle is presently expressed as a b2AABB, sometimes with a b2Transform for rotation.

It made sense at the time to reuse the data types, since they're always going in and out of the simulation and being largely fleshed out library side made them easy to work with. Expressing something like a node's range as a b2AABB meant that if I ever needed to find the closest object to it for some reason, I could easily reuse that data with a world query without having to convert it.

I can understand the desire to internalize b2AABB for performance reasons; if there are gains to be made then I'm sure that's the right move. I am guessing that if that happens, functions like b2ComputeCircleAABB will take pointers to b2Vec2s for returning the upper and lower bound results then? I'd also be alright with delivering the bounds directly to b2World_QueryAABB.

**Comment by erincatto** [comment]
I thought about this some more. I can still have a SIMD representation internally while offering the regular `b2AABB` externally. On the other hand did you look at these new functions?
```c
b2World_OverlapCircle
b2World_OverlapCapsule
b2World_OverlapPolygon
```

**Comment by ShockSlayer** [comment]
That sounds great. Best of both worlds. 

I'm excited to try them out; the added definition could definitely make a difference, especially using b2World_OverlapCircle since two of my current use cases for AABBs are radius based - and casting less shadows would be a performance improvement for sure.

**Comment by erincatto** [comment]
Thanks for the report. See #99
