### ISSUE TITLE
Restoring changing the density of existing shapes, and resetting the mass of a body

### ISSUE THREAD

**Issue by ShockSlayer** [erincatto/box2c#95]
I've noticed that there's no functions for getting or setting the density of a shape after creation. After making changes, in v2.4 I would also use ResetMassData to make sure that the body's mass is properly updated as well. It would be nice to have these back using the new systems.

EDIT: I also noticed that there's no getter for MassData either.

**Comment by erincatto** [comment]
I'll add a function to set the density. Not sure why it didn't update the mass. The new version will.

**Comment by ShockSlayer** [comment]
To be honest, I never actually checked if the mass data changed, but the Dynamics Module section of the v2.4 documentation stated "The mass of a body is not adjusted when you set the density. You must call ResetMassData for this to occur." so I just always did so on principal.

**Comment by erincatto** [comment]
Thanks for the report. See #99

**Comment by MohitSethi99** [comment]
I can't find public API for ResetMassData.
I expect there to be a way to reset/recalculate mass data if b2Body_SetMassData() exists to override it.

**Comment by erincatto** [comment]
I didn't consider that use case. I'll add the ResetMassData function.

**Comment by erincatto** [comment]
#119
