### ISSUE TITLE
Checking if a shape by ID is a sensor

### ISSUE THREAD

**Issue by ShockSlayer** [erincatto/box2c#97]
Currently working on migrating an AABB query callback that collects all shapes in an area, and I'd like to ignore any shapes that are sensors, but currently do not have a replacement for IsSensor. It would definitely be nice to have that function back. 

I was also thinking that this might also be a possibly good use case for adding another field to b2QueryFilter for ignoring sensors, since that might be useful for others as well.

**Comment by erincatto** [comment]
I'm adding `b2Shape_IsSensor`. Let's keep `b2QueryFilter` simple for now.

**Comment by erincatto** [comment]
Thanks for the report. See #99
